Feature 1188285245990833 - Case notes on organization and service
asylum-connect/control-panel pull request #53
Opened 2021-06-24 01:00 UTC by ky572

Notes added to organization and service schema in backend.

New UI component added to control panel which renders an "Updated At" tag to a child component. This component is used in a Notes container on the organization and service pages.

Tests added to backend for PATCHing notes to organization and service.

2021-06-29 23:18 UTC, FJKhan requested changes

2021-06-29 23:18 UTC, FJKhan commented on src/pages/Organization.js
> +      form: {fields: [{key: 'notes', label: 'Notes', type: 'textarea'}], initialValues: notes},
looks great!
see comment in corresponding PR in catalog API

2021-07-15 14:19 UTC, FJKhan approved these changes
Hey @ky572 , thanks for the updates! This looks great to me. a nice to have would be some spacing between the different notes as I'm not sure where one ends and the other begins. another option is to add a "view" action and truncate the displayed text. lmk what you think

![image](https://user-images.githubusercontent.com/7406914/125803121-91aa83a1-63e4-4246-b541-3222b48be0ac.png)

2021-07-16 16:30 UTC, ky572 commented
@FJKhan Fixed the table styling, check out the latest commit. Tables look a hell of a lot better now with that change.

2021-07-20 16:25 UTC, merged